# Generated by Django 4.0 on 2022-07-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='top_rating',
            field=models.BooleanField(default=False),
        ),
    ]
